apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns1
resources:
- namespace.yaml

bases:
- ../../../shared/ci-deployer
- ../../../shared/groups

generators:
- vcap-services.yaml

patchesStrategicMerge:
- |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: read-only-group
  subjects:
  - kind: Group
    name: oidc:SomeGroup
